name: Flask CI/CD to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login to ACR
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 3. Build Docker image
      - name: Build Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/flask-api:latest ./flask-api

      # 4. Push Docker image
      - name: Push Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/flask-api:latest

      # 5. Verify pushed image (optional)
      - name: List Images (debug)
        run: |
          echo "Image pushed successfully"
