name: Test GitHub Actions Pipeline

on:
push:
branches:
- main

jobs:
test-job:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Print message
    run: echo "🚀 Pipeline is working!"

  - name: Show files
    run: ls -la

  - name: Test Docker Build
    run: |
      docker build -t test-image ./flask-api

  - name: Run Container
    run: |
      docker run -d -p 5000:5000 test-image
      sleep 5
      curl http://localhost:5000 || echo "App not responding"
```
